### PR TITLE
Add NodeTicket FFI variant

### PR DESCRIPTION
**Pull request by niklaswimmer**
Adds the `NodeTicket` to the FFI crate. Basically a copy of the already existing `BlobTicket` and `DocTicket`.

I use this in an Android application of mine and it works as expected. I played with the idea of adding `from_bytes` and `to_bytes`, but ultimately decided to instead just do this small change for now as it is all I need right now.

Not sure if I need to generate any new files? Please let me know.

### CODE REVIEW

**Comment by dignifiedquire** [comment]
There is currently no API to create a node ticket in the FFI asfik, so I am curious how do you create these currently?

**Comment by niklaswimmer** [comment]
I am sorry, but I am not sure I understand your question. I currently just point my Android build to the code/lib generated from my fork, which is how I verified that this actually works.

**Comment by niklaswimmer** [comment]
Ohh just realized. You mean because there is no API to actually *create* a node ticket in FFI. Well, for my use case I just need to parse it :sweat_smile: 

You are right however that I should probably include a constructor.

**Comment by dignifiedquire** [comment]
I think it would be best to have a method to create a `NodeTicket` from a `NodeAddr`, can you add that?

**Comment by niklaswimmer** [comment]
I opted to change the default constructor to be `NodeAddr` -> `NodeTicket`, as that is also how `new` works for the `iroh-base` `NodeTicket` and I felt it makes more sense as the "entry" point of the object. Also added some comments to point people to new the `parse` method. Hope that is ok for you (otherwise I can of course do it the other way around too).

Ideally I think we should turn the following into non-fallible `Try` to remove the `Result` on this and a bunch of other constructors/methods (would require making an exported `SocketAddr` member that encapsulates the fallible string conversion). That can be done in another PR though. 
https://github.com/n0-computer/iroh-ffi/blob/1dbd961b131fe3c84915bf3934370b09317ed126/src/doc.rs#L557

**Review by dignifiedquire — APPROVED** [review]
thanks, I'll do the regeneration of files etc as a follow up

**Pull request merged**
