### PR TITLE
feat: upgrade to uniffi 0.28

### PR DESCRIPTION
**Pull request by dignifiedquire**
- Makes use of the new `Trait` feature and the improved error handling abilities

### CODE REVIEW

**Review by ramfox — APPROVED** [review]
Looks good.

We can also use the new `Trait` support to replace some of these weird custom `eq` and `to_string` methods, I'll write an issue that can be done in a follow up

**Comment by ramfox** [comment]
looks like some tests aren't passing, happy to look into this tomorrow if needed

**Comment by dignifiedquire** [comment]
need to revert the commits that add tests.. there is only support for linux in uniffi unfortunately

**Comment by dignifiedquire** [comment]
@ramfox ready for another review, reverted the problematic commits

**Review by ramfox — APPROVED** [review]

**Pull request merged**
